language: python

matrix:
  include:
    - python: "2.7"
      env: CHANNEL=defaults
    - python: "3.4"
      env: CHANNEL=defaults
    - python: "3.5"
      env: CHANNEL=defaults
    - python: "3.6"
      env: CHANNEL=conda-forge

before_install:
  - "wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh"
  - "chmod +x miniconda.sh"
  - "./miniconda.sh -b"
  - "export PATH=/home/travis/miniconda2/bin:$PATH"
  - "conda update --yes conda"
  - "conda info --all"

install:
  - "conda create --yes --name test-env --channel $CHANNEL python=$TRAVIS_PYTHON_VERSION numpy cython gdal pyproj shapely coverage"
  - "source activate test-env"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install . --no-deps"
  - "rm -rf karta/"   # clean-up to workaround coverage.py scanning karta/ dir
                      # while karta module is installed by pip elsewhere

script: coverage run --source=karta tests/runtests.py && coverage report
after_success: coveralls
sudo: false   # container-based testing

